steps:

# Report the diff in this change
- name: 'gcr.io/cloud-builders/git'
  args: ['diff', '--stat', 'HEAD~1', '--', '.']

# Images
- name: 'gcr.io/cloud-builders/docker'
  dir: hello-world
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/hello-world', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  dir: tor-relay
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/tor-relay', '.' ]

timeout: 600s

images:
- 'gcr.io/$PROJECT_ID/hello-world'
- 'gcr.io/$PROJECT_ID/tor-relay'
