steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/hello-world', 'hello-world' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/tor-relay', 'tor-relay' ]
images:
- 'gcr.io/$PROJECT_ID/hello-world'
- 'gcr.io/$PROJECT_ID/tor-relay'
