steps:

# Build the binary.
- name: 'gcr.io/cloud-builders/go'
  dir: changed_images
  args: ['install', 'cbuilder']
  env: ['GOPATH=.']
# Deepen the clone since GCB only gets --depth=1
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']
# Execute the binary to finding changed images
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args: ['-c', './changed_images/bin/cbuilder']
# Build changed images
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['./build-containers.sh', 'tobuild']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  - 'SHORT_SHA=$SHORT_SHA'

# Images
# - name: 'gcr.io/cloud-builders/docker'
#   dir: hello-world
#   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/hello-world', '.' ]

# - name: 'gcr.io/cloud-builders/docker'
#   dir: tor-relay
#   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/tor-relay', '.' ]

timeout: 600s

# images:
# - 'gcr.io/$PROJECT_ID/hello-world'
# - 'gcr.io/$PROJECT_ID/tor-relay'
